### ISSUE TITLE
Github Discussions

### ISSUE THREAD

**Issue by mrmetaverse** [AngellXR/metaversity#2]
We will use github discussions to: 

- hash out issues for the backlog
- ask and answer questions 
- keep meeting notes and set agendas
- share thoughts, readings, musings

**Comment by cruzluna** [comment]
Are there any tasks that need to be completed?

**Comment by mrmetaverse** [comment]
> Are there any tasks that need to be completed?

Working out the next kickoff. Hoping to get the group together sometime next week (maybe Monday?) to work through some of the known items. At the moment, the project has been on hold until more interest / bandwidth became available. There are a number of people reaching out lately to get involved so it is looking like we can start breaking down work into a backlog again. 

I am thinking we should give the project a new name. This initiative is one that many care about, but the name came from merging with another group who shared the same goals. Since adopting their name for the project, they became too busy and were no longer attending Monday meetings. If we are going to press forward with this again, it should be a name we can all rally around so there isn't any confusion from past parties who presented the original name.

This could be a nice ice breaker for our next kickoff. I will share more info before end of week.

**Comment by mrmetaverse** [comment]
Created our [second discussion](https://github.com/AngellXR/metaversity/discussions/7) based on the question asked above, and noticed another discussion there that I missed before. I am moving this ticket to done, and we can review it during kickoff.
